/* recognizeExp.c, Gerard Renardel, 29 January 2014
 *
 * In this file a recognizer acceptExpression is definined that can recognize
 * arithmetical expressions generated by the following BNF grammar:
 *
 * <expression>  ::= <term> { '+'  <term> | '-' <term> }
 *
 * <term>       ::= <factor> { '*' <factor> | '/' <factor> }
 *
 * <factor>     ::= <number> | <identifier> | '(' <expression> ')'
 *
 * Input for the recognizer is the token list constructed by the scanner (in scanner.c).
 * For the recognition of a token list the method of *recursive descent* is used.
 * It relies on the use of three functions for the recognition and processing of
 * terms, factors and expressions, respectively.
 * These three functions are defined with mutual recursion, corresponding with the
 * structure of the BNF grammar.
 */

#include <stdio.h>  /* getchar, printf */
#include <stdlib.h> /* NULL */
#include "scanner.h"
#include "recognizeEq.h"

/* The functions acceptNumber, acceptIdentifier and acceptCharacter have as
 * (first) argument a pointer to an token list; moreover acceptCharacter has as
 * second argument a character. They check whether the first token
 * in the list is a number, an identifier or the given character, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */
int maxDegree = 0;
int variable = 0;
char var;
int x = 0;

int degree(List *lp) {
    int d = 0;
    if (*lp != NULL && (*lp)->tt == Number && ((*lp)->t).number > d) {
        d = ((*lp)->t).number;
        return d;
    }
    return 0;
}

void oneVariable(List *lp) {
    if (*lp != NULL && (*lp)->tt == Identifier && x == 0) {
        var = *((*lp)->t).identifier;
        //printf("var: %c\n", var);
        x++;
    }
    if (*lp != NULL && (*lp)->tt == Identifier && var == *((*lp)->t).identifier) {
        var = *((*lp)->t).identifier;
    } else if (*lp != NULL && (*lp)->tt == Identifier && var != *((*lp)->t).identifier) {
        variable++;
    }
}

int acceptNumber(List *lp) {
  if (*lp != NULL && (*lp)->tt == Number) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptIdentifier(List *lp) {
  if (*lp != NULL && (*lp)->tt == Identifier) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

int acceptCharacter(List *lp, char c) {
  if (*lp != NULL && (*lp)->tt == Symbol && ((*lp)->t).symbol == c) {
    *lp = (*lp)->next;
    return 1;
  }
  return 0;
}

/* The functions acceptFactor, acceptTerm and acceptExpression have as
 * argument a pointer to a token list. They check whether the token list
 * has an initial segment that can be recognized as factor, term or expression, respectively.
 * When that is the case, they yield the value 1 and the pointer points to the rest of
 * the token list. Otherwise they yield 0 and the pointer remains unchanged.
 */

int acceptFactor(List *lp) {
  return
    (  acceptNumber(lp)
    || acceptIdentifier(lp)
    || ( acceptCharacter(lp,'(')
       && acceptExpression(lp)
       && acceptCharacter(lp,')')
      )
    );
}

int acceptTerm(List *lp) {
    if (acceptNumber(lp)) {
        oneVariable(lp);
        if (acceptIdentifier(lp)) {
            if (maxDegree == 0) {
                maxDegree = 1;
            }
            if (acceptCharacter(lp, '^')) {
                if (degree(lp) > maxDegree) {
                    maxDegree = degree(lp);
                }
                return acceptNumber(lp);
            }
        }
        return 1;
    } else {
        oneVariable(lp);
        if (acceptIdentifier(lp)) {
            if (maxDegree == 0) {
                maxDegree = 1;
            }
            if (acceptCharacter(lp, '^')) {
                if (degree(lp) > maxDegree) {
                    maxDegree = degree(lp);
                }
                return acceptNumber(lp);
            } else {
                return 1;
            }
        }
    }
  return 0;
}

int acceptExpression(List *lp) {
    if (acceptCharacter(lp, '-')) {
    }
    if (!acceptTerm(lp)) {
        return 0;
    }
    while (acceptCharacter(lp, '+') || acceptCharacter(lp, '-')) {
        if (!acceptTerm(lp)) {
            return 0;
        }
    } /* no + or -, so we reached the end of the expression */
    return 1;
}

int acceptEquation(List *lp) {
    if (acceptExpression(lp)) {
        if (acceptCharacter(lp, '=')) {
            acceptExpression(lp);
            return 1;
        }
    }
    return 0;
}

/* The function recognizeExpressions demonstrates the recognizer. */
void recognizeEquations() {
  char *ar;
  List tl, tl1;
  printf("give an equation: ");
  ar = readInput();
  while (ar[0] != '!') {
    tl = tokenList(ar);
      printList(tl);
    tl1 = tl;
    if (acceptEquation(&tl1) && tl1 == NULL) {
        if (variable == 0) {
            printf("this is an equation in 1 variable of degree %d\n", maxDegree);
        } else if (variable > 0) {
            printf("this is an equation, but not in 1 variable\n");
        }
    } else {
      printf("this is not an equation\n");
    }
      maxDegree = 0;
      variable = 0;
      x = 0;
    free(ar);
    freeTokenList(tl);
    printf("\ngive an equation: ");
    ar = readInput();
  }
  free(ar);
  printf("good bye\n");
}
